version: "3.8"

networks: 
    stake-app-network:

services: 
    sqlserver:
        image: "mcr.microsoft.com/mssql/server"
        container_name: sqlserver
        networks: 
            - stake-app-network
        restart: always
        environment: 
            - SA_PASSWORD=Dev@12345
            - ACCEPT_EULA=Y
        ports: 
            - "1433:1433"    
        
    web:
        container_name: web
        image: web
        build: 
            context: .
            dockerfile: ./StakeApp.Web/Dockerfile
        depends_on: 
            - sqlserver
        networks: 
            - stake-app-network
        restart: always
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
        ports: 
            - "5000:5000"
            - "5001:5001"                     
